# Generated by Django 3.0.6 on 2021-04-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='book',
            name='thumbnail',
        ),
    ]
