# Generated by Django 3.0.6 on 2021-05-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210501_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('added_at',)},
        ),
    ]
